name: Build site

on:
  pull_request:
    branches:
    - master
    - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Navigate to repo
      run: cd $GITHUB_WORKSPACE
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install deps
      run: yarn 
    - name: Install Workers script deps
      run: yarn global add  @cloudflare/wrangler 
    - name: Build docs
      run: yarn workspace cloudflare-workers-docs run build
    - name: Build Workers script
      run: yarn workspace cloudflare-workers-docs run worker-build
